// Drugs offered on the home page, chosen from the Gate 1 review set
// (apps/worker/scripts/review_set.txt). A fixed list, never built from what visitors look up,
// so the page shows nothing about anyone's searches and needs no request to draw.
export const FEATURED_DRUGS: readonly string[] = [
  'atorvastatin',
  'lisinopril',
  'amlodipine',
  'metoprolol',
  'losartan',
  'warfarin',
  'apixaban',
  'metformin',
  'levothyroxine',
  'sertraline',
  'escitalopram',
  'fluoxetine',
  'bupropion',
  'trazodone',
  'alprazolam',
  'zolpidem',
  'gabapentin',
  'lamotrigine',
  'sumatriptan',
  'tramadol',
  'prednisone',
  'albuterol',
  'montelukast',
  'ondansetron',
  'amoxicillin',
  'azithromycin',
  'doxycycline',
  'ciprofloxacin',
  'sildenafil',
  'tamsulosin',
  'ibuprofen',
  'acetaminophen',
  'naproxen',
  'aspirin',
  'Tylenol PM',
  'loratadine',
  'cetirizine',
  'diphenhydramine',
  'pseudoephedrine',
  'guaifenesin',
  'omeprazole',
  'famotidine',
  'loperamide',
  'bismuth subsalicylate',
  'hydrocortisone',
  'nicotine',
]
